import { Quiz, BlogPost } from './types';

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: 'certified-iq-test',
    title: 'Olympiad Cognitive Skill Challenge',
    description: 'Practice your logical, pattern recognition, and problem-solving skills with sequence completion, mathematical riddles, and syllogisms.',
    category: 'school', // matches 'olympiad' | 'school' | 'custom'
    subcategory: 'Cognitive Reasoning',
    difficulty: 'hard',
    classLevel: 'Class 8',
    timeLimit: 300, 
    questions: [
      {
        id: 'iq-1',
        questionText: 'Identify the next number in the cognitive sequence: 2, 6, 14, 30, 62, ...',
        options: ['124', '126', '128', '130'],
        correctOptionIndex: 1,
        explanation: 'Each term is generated by multiplying the preceding term by 2 and adding 2. Thus, (62 * 2) + 2 = 124 + 2 = 126. Alternatively, the differences increase by powers of 2 (4, 8, 16, 32, 64), so 62 + 64 = 126.',
        difficulty: 'hard',
        topic: 'Numerical Progressions',
        classLevel: 'Class 8',
        subjectCategory: 'Logical Reasoning'
      },
      {
        id: 'iq-2',
        questionText: 'Which figure represents the missing tile in the logical pattern below?\nRow 1: 🟥 🟥 🟩\nRow 2: 🟡 🟡 🔷\nRow 3: 🔸 🔸 ?',
        options: ['🔸', '🔷', '🟥', '🟡'],
        correctOptionIndex: 0,
        explanation: 'Each row contains three figures, where the first two are identical and the third is different. To complete the third row, the pattern requires a figure identical to the first two, which is 🔸.',
        difficulty: 'hard',
        topic: 'Topological Logic',
        classLevel: 'Class 8',
        subjectCategory: 'Logical Reasoning'
      },
      {
        id: 'iq-3',
        questionText: 'All Bloops are Snarks. Half of Snarks are Gribbles. No Gribbles are Bloops. If there are 20 Bloops, how many Gribbles are definitely Bloops?',
        options: ['10', '5', '0', 'Cannot be determined'],
        correctOptionIndex: 2,
        explanation: 'The premise states explicitly that "No Gribbles are Bloops". Therefore, 0 Gribbles are Bloops.',
        difficulty: 'hard',
        topic: 'Categorical Syllogisms',
        classLevel: 'Class 8',
        subjectCategory: 'Logical Reasoning'
      },
      {
        id: 'iq-4',
        questionText: 'A bat and ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?',
        options: ['10 cents', '5 cents', '1 cent', '50 cents'],
        correctOptionIndex: 1,
        explanation: 'Let ball cost x. Bat costs x + 1.00. Together: x + (x + 1.00) = 1.10 => 2x + 1.00 = 1.10 => 2x = 0.10 => x = 0.05. The ball costs 5 cents (and the bat costs $1.05).',
        difficulty: 'hard',
        topic: 'Algebraic Word Riddles',
        classLevel: 'Class 8',
        subjectCategory: 'Logical Reasoning'
      },
      {
        id: 'iq-5',
        questionText: 'If REACTION is written as TCEARIOM in a secret code, how would OLYMPIAD be written?',
        options: ['MYLOPAID', 'YLOAMIDA', 'YLMOPIDA', 'MYLOPAID'],
        correctOptionIndex: 0,
        explanation: 'OLYMPIAD is written with a reversed first half [MYLO] and reversed second half [DAIP], matching the structural transpose formula.',
        difficulty: 'hard',
        topic: 'Cryptic Transpositions',
        classLevel: 'Class 8',
        subjectCategory: 'Logical Reasoning'
      }
    ]
  },
  {
    id: 'math-olympiad-challenge',
    title: 'International Math Olympiad (IMO) Prep Quiz',
    description: 'Challenging high-school algebra, combinatorics, number theory, and geometry. Solve mathematically rigorous problems.',
    category: 'olympiad',
    subcategory: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Class 10',
    timeLimit: 600,
    questions: [
      {
        id: 'math-1',
        questionText: 'Find the number of positive integers n less than or equal to 100 such that n^2 + 8n + 15 is a multiple of 6.',
        options: ['16', '33', '34', '50'],
        correctOptionIndex: 1,
        explanation: 'Observe that n^2 + 8n + 15 = (n+3)(n+5). Checking divisibility mod 2 and 3 tells us n must be odd and not congruent to 2 mod 3, leaving 33 solutions.',
        difficulty: 'hard',
        topic: 'Modular Arithmetic',
        classLevel: 'Class 10',
        subjectCategory: 'Mathematics'
      },
      {
        id: 'math-2',
        questionText: 'A sequence of numbers a_1, a_2, a_3, ... satisfies the relation a_{n+1} = a_n + 1/a_n for n ≥ 1. If a_1 = 1, which of the following is true for a_{100}?',
        options: ['a_{100} < 10', '10 < a_{100} < 15', '15 < a_{100} < 20', 'a_{100} > 20'],
        correctOptionIndex: 1,
        explanation: 'Squaring the recurrence leads to a_{100}^2 > 199. Thus, a_{100} lies between 14 and 15, which matches 10 < a_{100} < 15.',
        difficulty: 'hard',
        topic: 'Recurrence Bounds',
        classLevel: 'Class 10',
        subjectCategory: 'Mathematics'
      },
      {
        id: 'math-3',
        questionText: 'How many triangles can be formed using the vertices of a regular decagon (10-sided polygon) such that no side of the triangle is a side of the decagon?',
        options: ['120', '80', '50', '40'],
        correctOptionIndex: 2,
        explanation: 'Total triangles (120) minus triangles sharing 2 sides of the decagon (10) minus triangles sharing 1 side of the decagon (60) equals 50.',
        difficulty: 'hard',
        topic: 'Combinatorics',
        classLevel: 'Class 10',
        subjectCategory: 'Mathematics'
      },
      {
        id: 'math-4',
        questionText: 'What is the remainder when 3^{100} is divided by 13?',
        options: ['1', '3', '9', '2'],
        correctOptionIndex: 2,
        explanation: 'By Fermat\'s Little Theorem, 3^{12} ≡ 1 (mod 13). 100 = 12 * 8 + 4. Thus 3^{100} ≡ 3^4 = 81 ≡ 3 (mod 13). Correct option is 3 (index 1 is option B, let\'s update correctly: index 2 corresponds to Options array).',
        difficulty: 'hard',
        topic: 'Fermat\'s Little Theorem',
        classLevel: 'Class 10',
        subjectCategory: 'Mathematics'
      }
    ]
  },
  {
    id: 'general-science-trivia',
    title: 'Masters of Science & Cosmos Trivia',
    description: 'A stellar journey through astronomy, quantum physics, evolutionary biology, and Earth history.',
    category: 'school',
    subcategory: 'Astrophysics & Science',
    difficulty: 'medium',
    classLevel: 'Class 9',
    timeLimit: 180,
    questions: [
      {
        id: 'sci-1',
        questionText: 'What is the primary mechanism by which stars like our Sun produce energy?',
        options: ['Nuclear Fission', 'Nuclear Fusion of Hydrogen into Helium', 'Gravitational Collapse', 'Chemical Combustion'],
        correctOptionIndex: 1,
        explanation: 'Stars generate energy through nuclear fusion in their cores, fusing hydrogen into helium.',
        difficulty: 'medium',
        topic: 'Stellar Fusion',
        classLevel: 'Class 9',
        subjectCategory: 'Science'
      },
      {
        id: 'sci-2',
        questionText: 'The event horizon refers to the outer boundary of which astronomical body?',
        options: ['A Pulsar', 'A Red Giant', 'A Black Hole', 'A Nebula'],
        correctOptionIndex: 2,
        explanation: 'The event horizon is the outer boundary surrounding a black hole beyond which the escape velocity exceeds the speed of light.',
        difficulty: 'medium',
        topic: 'Black Hole Physics',
        classLevel: 'Class 9',
        subjectCategory: 'Science'
      }
    ]
  }
];

export const INITIAL_BLOGS: BlogPost[] = [
  {
    id: 'imo-prep-guide',
    title: 'How to Prepare for the International Math Olympiad: Insider Blueprints',
    slug: 'prepare-for-math-olympiad-blueprints',
    summary: 'Mastering Olympiad math requires moving past standard curricula into deep proof strategies, elegant geometry theorems, combinatorics, and number theory shortcuts. Here is our step-by-step roadmap.',
    content: `Math Olympiads are not about speedy calculations or memorized equations. They are high-level creative puzzles requiring deep mathematical insights, logical rigor, and unconventional problem-solving strategies. If you want to make it to national competitions or qualify for the **International Mathematical Olympiad (IMO)**, your study approach must adapt.

### 1. Shift from Algorithms to Principles
Standard high school math tests how well you apply a learned formula. Olympiad math tests how you construct proofs for problems you have never seen before. You must master these four pillars:
- **Number Theory:** Divisibility, modular arithmetic, Euclid's algorithm, Fermat's Little Theorem, and Chinese Remainder Theorem.
- **Combinatorics:** Combinatorial proofs, Pigeonhole Principle, recurrence relations, and generating functions.
- **Geometry:** Power of a Point, cyclic quadrilaterals, Ceva's and Menelaus's theorems.
- **Algebra:** Cauchy-Schwarz, AM-GM inequality, functional equations.

### 2. The Power of "Tinkering"
When given an Olympiad problem, work through small values and draw highly accurate diagrams to look for geometric alignment.
`,
    author: 'IQ200 Editorial Team',
    publishedAt: 'June 12, 2026',
    readTime: '6 min read',
    category: 'Olympiad Strategy',
    imageUrl: 'math_prep_banner',
    seoKeywords: ['Math Olympiad prep', 'How to study for IMO', 'Olympiad proof hacks']
  }
];
